#!/usr/bin/env python3
"""Create run artifacts (summary + plots) from SPAI inference CSV and optionally upload to Hugging Face Hub."""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
import re

import matplotlib.pyplot as plt
import pandas as pd

try:
    from huggingface_hub import HfApi
    HF_AVAILABLE = True
except ImportError:
    HF_AVAILABLE = False


def _pick_score_column(df: pd.DataFrame) -> Optional[str]:
    preferred = ["spai", "score", "prediction", "pred"]
    lower_map = {c.lower(): c for c in df.columns}
    for col in preferred:
        if col in lower_map:
            return lower_map[col]

    ignored = {"image", "split", "class", "label", "target"}
    for col in df.columns:
        if col.lower() in ignored:
            continue
        if pd.api.types.is_numeric_dtype(df[col]):
            return col
    return None


def _save_histogram(df: pd.DataFrame, score_col: str, output_dir: Path) -> Path:
    fig_path = output_dir / "score_histogram.png"
    plt.figure(figsize=(9, 5))
    plt.hist(df[score_col].astype(float), bins=30)
    plt.title(f"SPAI Score Distribution ({score_col})")
    plt.xlabel(score_col)
    plt.ylabel("Count")
    plt.tight_layout()
    plt.savefig(fig_path, dpi=150)
    plt.close()
    return fig_path


def _save_pred_bar(df: pd.DataFrame, output_dir: Path, threshold: float) -> Path:
    fig_path = output_dir / "predicted_label_counts.png"
    pred = (df["predicted_label"].astype(int)).value_counts().sort_index()
    labels = ["real (0)", "ai-generated (1)"]
    values = [int(pred.get(0, 0)), int(pred.get(1, 0))]

    plt.figure(figsize=(7, 4))
    plt.bar(labels, values)
    plt.title(f"Predicted Labels (threshold={threshold})")
    plt.ylabel("Count")
    plt.tight_layout()
    plt.savefig(fig_path, dpi=150)
    plt.close()
    return fig_path


def _build_summary(df: pd.DataFrame, score_col: str, threshold: float) -> dict:
    scores = df[score_col].astype(float)
    pred = (scores >= threshold).astype(int)
    df["predicted_label"] = pred

    summary = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "rows": int(len(df)),
        "score_column": score_col,
        "threshold": threshold,
        "score_min": float(scores.min()),
        "score_max": float(scores.max()),
        "score_mean": float(scores.mean()),
        "predicted_real_count": int((pred == 0).sum()),
        "predicted_ai_count": int((pred == 1).sum()),
    }

    if "class" in df.columns:
        try:
            gt = df["class"].astype(int)
            summary.update({
                "gt_real_count": int((gt == 0).sum()),
                "gt_ai_count": int((gt == 1).sum()),
                "agreement_count": int((gt == pred).sum()),
                "agreement_ratio": float((gt == pred).mean()),
            })
        except Exception:
            pass

    return summary


def _upload_to_hf(folder: Path, repo_id: str, token: str, commit_message: str) -> None:
    if not HF_AVAILABLE:
        raise RuntimeError("huggingface_hub is not installed. Run: pip install huggingface_hub")

    api = HfApi(token=token)
    api.create_repo(repo_id=repo_id, repo_type="dataset", exist_ok=True)
    api.upload_folder(
        folder_path=str(folder),
        repo_id=repo_id,
        repo_type="dataset",
        commit_message=commit_message,
    )


def _validate_hf_inputs(repo_id: str, token: str) -> tuple[str, str]:
    repo_id = repo_id.strip()
    token = token.strip()

    # Requests headers must be latin-1 encodable. Reject unsafe characters early.
    try:
        repo_id.encode("latin-1")
        token.encode("latin-1")
    except UnicodeEncodeError as exc:
        raise RuntimeError(
            "HF repo id/token contains non-latin characters. Copy them again from Hugging Face."
        ) from exc

    if not re.fullmatch(r"[A-Za-z0-9._-]+/[A-Za-z0-9._-]+", repo_id):
        raise RuntimeError(
            f"Invalid HF repo id '{repo_id}'. Expected format: username/repo-name"
        )

    return repo_id, token


def main() -> None:
    parser = argparse.ArgumentParser(description="Create SPAI execution artifacts and optionally upload to Hugging Face Hub")
    parser.add_argument("--results-csv", type=Path, required=True, help="CSV generated by SPAI inference")
    parser.add_argument("--output-dir", type=Path, required=True, help="Directory where artifacts will be written")
    parser.add_argument("--log-file", type=Path, default=None, help="Optional run log file")
    parser.add_argument("--err-file", type=Path, default=None, help="Optional run error file")
    parser.add_argument("--threshold", type=float, default=0.5, help="Threshold to derive predicted label from score")
    parser.add_argument("--hf-repo-id", type=str, default=None, help="HF dataset repo id (username/repo)")
    parser.add_argument("--hf-token", type=str, default=None, help="HF token; defaults to HF_TOKEN env var")
    parser.add_argument("--commit-message", type=str, default="Upload SPAI execution artifacts")
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(args.results_csv)
    score_col = _pick_score_column(df)
    if score_col is None:
        raise RuntimeError(f"Could not find score column in {args.results_csv}")

    summary = _build_summary(df, score_col=score_col, threshold=args.threshold)

    enriched_csv = args.output_dir / "predictions_enriched.csv"
    df.to_csv(enriched_csv, index=False)

    summary_path = args.output_dir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    _save_histogram(df, score_col=score_col, output_dir=args.output_dir)
    _save_pred_bar(df, output_dir=args.output_dir, threshold=args.threshold)

    if args.log_file and args.log_file.exists():
        (args.output_dir / args.log_file.name).write_text(args.log_file.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")
    if args.err_file and args.err_file.exists():
        (args.output_dir / args.err_file.name).write_text(args.err_file.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")

    hf_repo_id = args.hf_repo_id or os.getenv("HF_EXEC_REPO_ID")
    hf_token = args.hf_token or os.getenv("HF_TOKEN")
    if hf_repo_id and hf_token:
        try:
            hf_repo_id, hf_token = _validate_hf_inputs(hf_repo_id, hf_token)
            _upload_to_hf(args.output_dir, repo_id=hf_repo_id, token=hf_token,
                          commit_message=args.commit_message)
            print(f"Uploaded execution artifacts to https://huggingface.co/datasets/{hf_repo_id}")
        except Exception as exc:
            print(f"HF upload failed: {exc}")
            print("Artifacts were still created locally.")
    else:
        print("HF upload skipped (set HF_EXEC_REPO_ID and HF_TOKEN to enable upload).")

    print(f"Artifacts written to: {args.output_dir}")


if __name__ == "__main__":
    main()
